### ISSUE TITLE
Dumping Gamecube games?

### ISSUE THREAD

**Issue by Danfun64** [saramibreak/DiscImageCreator#144]
I have successfully dumped my very small Wii collection. However, I am having trouble dumping the two Gamecube games I own. Somehow I feel like the command that was acceptable for Wii dumps isn't as acceptable for Gamecube dumps. I am using a GDR8084N DVD Drive. A log of the cmd output of three attempted rips (two Wii games, one Gamecube game) is attached.
[log.txt](https://github.com/saramibreak/DiscImageCreator/files/9439102/log.txt)
.

**Comment by saramibreak** [comment]
Is this bug report? If yes, use "Bug report" not "Open a blank issue".

**Comment by Danfun64** [comment]
I'm honestly not sure if this is a bug report or not... perhaps it is. It's either a bug with the program (the exact command that works with Wii games should work with Gamecube games) or a bug with the instructions (there is an alternative command with the Gamecube's smaller size both GB wise and physically)

**Comment by saramibreak** [comment]
> I'm honestly not sure if this is a bug report or not...

Ok, but I want to see 3 discs logs you dumped.

**Comment by Danfun64** [comment]
Do you want me to upload the _DMI.bin and _PFI.bin files as well as the .txt files?

**Comment by Danfun64** [comment]
This is a 7z containing all the zips, including the rawReadable txts.
https://drive.google.com/file/d/1bT9NviBbt-q6CAQNK_5ySBToqglPC3Zz/view?usp=sharing

**Comment by saramibreak** [comment]
> GoldeneyeWii

Failed to analize __dec (Track xx).iso_ after .iso was decrypted.

```
========== NintendoOpticalDiscFS ==========
========== Disc Header ==========
	                                 Disc ID: m
	                               Game Code: o�
	                             Region Code: �
	                              Maker Code: "�
	                             Disc Number: 142
	                                 Version: 226
	                         Audio Streaming: 63
	                      Stream Buffer Size: 156
	                               Game Name: V��"�Qd8����Nt�*���W[�S�

	      offset of debug monitor (dh.bin) ?: 3880904171 (0xe751e5eb)
	        addr (?) to load debug monitor ?: 0x722eacb4
	offset of main executable DOL (bootfile): 3220849688 (0xbffa4418)
	             offset of the FST (fst.bin): 457698748 (0x1b47edbc)
	                             size of FST: 3178686750 (0xbd76e91e)
	                     maximum size of FST: 2790997473 (0xa65b3de1)
	                       user position (?): 0x80424ef4
	                         user length (?): 3578150132 (0xd5463cf4)
	                                 unknown: 3860557381 (0xe61b6e45)
```

structure of Disc Header
http://hitmen.c02.at/files/yagcd/yagcd/chap13.html#sec13.1

By the way, does _LEGO Indiana Jones_ and _James Bond: Golden Eye_ only have this problem? Are other wii discs no problem?

**Comment by Danfun64** [comment]
It seems like all of the Wii games I have struggle with the decoding
process, though I don't care all that much. Dolphin accepts the unscrambled
4.5GB ISOs just fine (at least with installed NAND? I don't know if that
makes a difference and I can't check this very second) and I could compress
the ISOs using it.

My main problem is with my two GameCube games more or less refusing to dump
at all.

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/9477999/DiscImageCreator_test.zip)
Fixed. It was a clearly bug when I committed 22e5812b234d8db8d0ef132f6576ba38250a460d

**Comment by Danfun64** [comment]
This worked enough for me. the post unscrambling step is still buggy though lol. Has the code for this build been uploaded to github?

**Comment by saramibreak** [comment]
committed https://github.com/saramibreak/DiscImageCreator/commit/0285795bb3811c74ca981debbd5a840921ccb206

> the post unscrambling step is still buggy

I dumped Metal Slug Complete (Japan), and it's no problem. I'll get _LEGO Indiana Jones_ or _James Bond: Golden Eye_ or other USA wii discs in the future.
