### ISSUE TITLE
/r option for DVDs ignores other flags (such as /rr and /ps)

### ISSUE THREAD

**Issue by TheRogueArchivist** [saramibreak/DiscImageCreator#214]
**Version**
32 bit, AnsiBuild, 20230413T211754

**Describe the bug**
When trying to dump a disc with Alpha-ROM that has intentional bad sectors, DIC is unable to finish a reverse dump with /r since it ignores flags such as /rr or /ps, causing the dump to always error out once it reaches the bad sectors. Specific logs are included for the disc I used, but this can be seen on any DVD at all that might need flags such as /rr or /ps. I triple checked, and the sector range used is the correct range to dump the entire disc.

**Screenshots**
```
.\DiscImageCreator.exe dvd D "E:\MPF\ISO\MBACverB_Rev\MBACverB_Rev.iso" 16 /r 0 1237023 /rr 1 /ps 0
AppVersion
        32 bit, AnsiBuild, 20230413T211754
CurrentDirectory
        E:\MPF\Programs\Creator
WorkingPath
         Argument: E:\MPF\ISO\MBACverB_Rev\MBACverB_Rev.iso
         FullPath: E:\MPF\ISO\MBACverB_Rev\MBACverB_Rev.iso
            Drive: E:
        Directory: \MPF\ISO\MBACverB_Rev\
         Filename: MBACverB_Rev
        Extension: .iso
StartTime: 2023-05-27T02:52:35-0600
Set the drive speed: 22160KB/sec
DiskSize of [E:\MPF\ISO\MBACverB_Rev]
        Total:  5275247439872 bytes
         Used:  5251450630144 bytes
        ---------------------------
        Space:    23796809728 bytes
         => There is enough disk space for dumping
LBA[1233359, 0x12d1cf]: [F:ReadDVDReverse][L:77]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
EndTime: 2023-05-27T02:54:36-0600```

**Log file**
[MBACverB Logs.zip](https://github.com/saramibreak/DiscImageCreator/files/11581386/MBACverB.Logs.zip)

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11584838/DiscImageCreator_test.zip)
Added, but not test.

**Comment by TheRogueArchivist** [comment]
It'll be a while before it finishes running since I'm attempting to dump the whole disc, but there seems to be an issue that's popped up.

```LBA[1232013, 0x12cc8d]: [F:ReadDVDReverse][L:78]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 03-11-05 = MEDIUM_ERROR - L-EC UNCORRECTABLE ERROR
Read retry from 1236980 (Pass 1/1)```

The sector number mentioned first "LBA[1232013" doesn't match the second one "Read retry from 1236980". I'm not sure if it's only a visual bug or if it actually affects the dump.

**Comment by saramibreak** [comment]
Some fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11587706/DiscImageCreator_test.zip)

**Comment by TheRogueArchivist** [comment]
It looks like the sector numbers not matching is fixed now, thank you! There's a different bug that I just found though, DIC keeps trying to read reversed into negative sectors indefinitely, because it pads those with 00 when the read fails and keeps going in reverse forever. Here's the logs from a test dump I did to check the bug.
[DIC 214 Logs.zip](https://github.com/saramibreak/DiscImageCreator/files/11593221/DIC.214.Logs.zip)

**Comment by TheRogueArchivist** [comment]
Also, would it be possible to have an option to have the image be rearranged after so that it outputs as a normal image (starting with the first sector read, ending with the last sector read)? Basically I want to compare a full normal dump of the disc with a full reversed dump of the disc and see if there's any differences.

**Comment by saramibreak** [comment]
Some fixed.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11596528/DiscImageCreator_test.zip)

**Comment by TheRogueArchivist** [comment]
The bugs I mentioned before all seem to be fixed, but now on creating the non-reversed image after the dump was completed, I get an error that just says ``Failed to read [F:ReadDVDReverse][L:120]`` after writing EXACTLY 2 GiB (2,147,483,648 bytes) of the second image, so the original reversed image is complete but the second one isn't.
[DIC 214 Logs 2.zip](https://github.com/saramibreak/DiscImageCreator/files/11607841/DIC.214.Logs.2.zip)

**Comment by saramibreak** [comment]
> after writing EXACTLY 2 GiB

fixed seek32 -> seek64
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11608019/DiscImageCreator_test.zip)

**Comment by TheRogueArchivist** [comment]
Still the same exact issue, down to the byte of the file and error message given. I triple checked, and I'm on the latest test version you sent: ``32 bit, AnsiBuild, 20230531T113049``

**Comment by saramibreak** [comment]
Fixed seek offset.
[DiscImageCreator_test.zip](https://github.com/saramibreak/DiscImageCreator/files/11642366/DiscImageCreator_test.zip)

**Comment by TheRogueArchivist** [comment]
Seems to work for me! Finished dumping the disc fully and got a usable ISO.
