### ISSUE TITLE
Dump sector range (/ra) for BD discs too

### ISSUE THREAD

**Issue by JohnVeness** [saramibreak/DiscImageCreator#287]
**Is your feature request related to a problem? Please describe.**
Similar to issue #211 I have a Blu-ray disc that has an unreadable part. I'd like to be able to check how well cleaning the disc is working without having to dump the entire disc.

**Describe the solution you'd like**
A way to dump a sector range on BDs, like the existing /ra option for DVDs.

**Describe alternatives you've considered**
Putting up with the length of time it takes to dump from the start up to the bad patch!

**Additional context**
Also, as far as I can see, the /ra option isn't documented anywhere, e.g. in the help text.

Thanks!

**Comment by saramibreak** [comment]
[DiscImageCreator_test.zip](https://github.com/user-attachments/files/16561294/DiscImageCreator_test.zip)
added /ra to the bd command.

> Also, as far as I can see, the /ra option isn't documented anywhere, e.g. in the help text.

Thanks.

**Comment by JohnVeness** [comment]
> [DiscImageCreator_test.zip](https://github.com/user-attachments/files/16561294/DiscImageCreator_test.zip) added /ra to the bd command.

Thanks, although I'm running this on Linux. If you can point me to the source for this change, I can compile it...

**Comment by saramibreak** [comment]
Uploaded source code.

**Comment by JohnVeness** [comment]
Many thanks. I have tested that and it works as expected with a start and end argument :)

However, I notice that if I leave out one or both of the arguments after /ra, it will segmentation fault.

**Comment by saramibreak** [comment]
> However, I notice that if I leave out one or both of the arguments after /ra, it will segmentation fault.

Tell me all arguments, plz.

**Comment by JohnVeness** [comment]
For example:
`DiscImageCreator bd /dev/sr0 DISCNAME 0 /q /d /rr /ra 100000`
or
`DiscImageCreator bd /dev/sr0 DISCNAME 0 /q /d /rr /ra`
both of which segfault.

For interest (and this isn't really a feature request) I was trying the first form, with just the StartLBA, because I was hoping it would interpret that as meaning "dump from StartLBA to the end of the disc" and I hadn't yet looked up the end LBA of the disc. I only tried the second form to see if that would segfault too, which it did.

**Comment by saramibreak** [comment]
> both of which segfault.

Fixed it.

**Comment by JohnVeness** [comment]
Thanks, that seems to work great :)

**Comment by JohnVeness** [comment]
Also note https://github.com/saramibreak/DiscImageCreator/commit/2bce5d166d518ed3bd8c1fb66909d41bdb34e8d3#r145248358 if you missed it...
